### ISSUE TITLE
Decompiled source code of Death Rally available?

### ISSUE THREAD

**Issue by neuromancer** [enriquesomolinos/DreeRally#20]
I just found this: https://github.com/urxp/drally

**Comment by enriquesomolinos** [comment]
hi,

this is othrr project that try to reassemble the 1996 dos game version. It supose to be working, so it could be interesting showing and obtaining information to uae in dreerally.

**Comment by 1Simo1** [comment]
Hi,

if I can express an opinion, it looks like a code just decompiled and perhaps, in reverse, urxp can find also your DreeRally project very useful to reimplement code. I'm saying this because many lines of drally project code seem just decompiled. Of course, as said, all this IMHO :)

**Comment by neuromancer** [comment]
Paging @urxp
