### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by cxong** [enriquesomolinos/DreeRally#32]
**Is your feature request related to a problem? Please describe.**
Please add a license file to this project.
- Make it easy to identify the license for this project - e.g. GitHub can scan a `LICENSE` file and include it in the header
- Better legal protection when a proper license is used (some jurisdictions do not recognise public domain)

**Describe the solution you'd like**
I suggest Unlicense (https://choosealicense.com/licenses/unlicense/) or CC0 (https://creativecommons.org/share-your-work/public-domain/cc0/)

Copy the license text into a file at the project root like `LICENSE`, `LICENSE.md`, `COPYING`, or `COPYING.md`

**Describe alternatives you've considered**
See above

**Additional context**
See https://help.github.com/en/articles/licensing-a-repository for more info

**Comment by enriquesomolinos** [comment]
LICENSE-CC-BY-4.0.md was selected
